from datetime import timedelta
from GYM import db, app
from GYM.models import User, Plan, Equipment, Coach
with app.app_context():
    db.drop_all()
    db.create_all()
    # user = User(username = "test1", email = "kay1@gmail.com", password = "password", phone = "0123456789")
    # db.session.add(user)
    # user = User(username = "test2", email = "kay2@gmail.com", password = "password", phone = "1123456789")
    # db.session.add(user)
    plan = Plan(name = "7 Days", price = 500, duration = timedelta(days = 7))
    db.session.add(plan)
    plan = Plan(name = "1 Month", price = 2000, duration = timedelta(days= 30))
    db.session.add(plan)
    plan = Plan(name = "6 Months", price = 500, duration = timedelta(days = 180))
    db.session.add(plan)
    plan = Plan(name = "1 Year", price = 500, duration = timedelta(days = 365))
    db.session.add(plan)
    equipment = Equipment(name = "Treadmill", quantity = 1)
    db.session.add(equipment)
    equipment = Equipment(name = "10 lbs Dumbell", quantity = 3)
    db.session.add(equipment)
    equipment = Equipment(name = "15 lbs Dumbell", quantity = 6)
    db.session.add(equipment)
    equipment = Equipment(name = "20 lbs Dumbell", quantity = 12)
    db.session.add(equipment)
    # db.session.add(user)
    # user = User(username = "kay2", email = "kay2@gmail.com", password = "password")
    # db.session.add(user)
    coach = Coach(name = "Khoi", email = "khoi@gmail.com", phone = "0835952097")
    db.session.add(coach)
    coach = Coach(name = "Tin", email = "Tin@gmail.com", phone = "0123456789")
    db.session.add(coach)
    coach = Coach(name = "Vi", email = "Vi@gmail.com", phone = "0666888111")
    db.session.add(coach)
    db.session.commit()
